name: Run Telegram Bot

on:
  push:
    branches:
      - main  # Runs on push to the main branch
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checks out the repository code

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Specify the version of Python you want to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests python-telegram-bot

    - name: Run the bot
      env: 
        TELEGRAM_API_TOKEN: ${{ secrets.TELEGRAM_API_TOKEN }}  # Use GitHub Secrets for sensitive data
        TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
      run: python bot.py  # Replace with your bot script filename
      
